server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Revenco123
    hikari:
      maximum-pool-size: 20
    driver-class-name: org.gjt.mm.mysql.Driver